### ISSUE TITLE
checkpoint files not working

### ISSUE THREAD

**Issue by fkgruber** [noc-lab/MHCI-peptide-binding#1]
Hi
The 3 google drive for the links to the checkpoints for the models are invalid
[ESM1b (domain adaptation + fine-tuning)](https://drive.google.com/drive/folders/1Vxug83pC3DL7pug24f5UpqRPJqYCbt3K?usp=share_link)

[ESM2-650M (domain adaptation + fine-tuning)](https://drive.google.com/drive/folders/1WYWI3NQzKmzroo1SSrpaV5hDqZhgf7PO?usp=share_link)

[ESM2-3B (domain adaptation + fine-tuning)](https://drive.google.com/drive/folders/1X6hyZFRRJi1rimdoh0_iPn5c9AfbItWd?usp=share_link)
![image](https://github.com/user-attachments/assets/a51c88e6-6b7c-42fc-8227-4fe738ed0436)

**Comment by BoranHao** [comment]
Thank you for your feedback! This was due to a file migration on Google Drive requested by BU. We have updated the links and they should work now.
